version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_fitness
    restart: always
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development

  db:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my_password
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
